image_collector_node:
  ros__parameters:
    capture_period: 1.0
    dataset_dir: /data/datasets/image_collector/train
    blurry_dir: /data/datasets/image_collector/blurry
    save_imgs: True
    blur_thres: 35.0  # lower makes filter less strict (i.e. tolerate more blur in train)
    wipe_prev: True
    image_topic: /image_raw
    odom_topic: /odom